markdown: redcarpet
sass:
  style: :compressed
exclude: ["Rakefile", "Gemfile*", "README.md", "vendor"]
destination: _site
branch: source
defaults:
  -
    scope:
      path: "" # addresses every file
    values:
      layout: default
