markdown: redcarpet
sass:
  style: :compressed
exclude: ["Rakefile", "Gemfile*", "README.md", "vendor"]
destination: _site
gems:
  - bourbon
  - jekyll-assets
  - neat
defaults:
  -
    scope:
      path: "" # addresses every file
    values:
      layout: default
collections:
  meetups:
    output: true
    permalink: /meetups/:path/
